name: xplor
description: xplor

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # connectivity: ^1.0.0
  connectivity: ^0.4.4
  intl: any
  provider: ^4.3.2+2
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.12
  carousel_slider: ^2.2.1
  toast: ^0.1.5
  email_validator: '^1.0.0'
  pin_code_text_field: ^1.4.0
  dio: ^3.0.8
  pull_to_refresh: 1.6.3
  country_pickers: ^1.3.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_messaging: ^7.0.3
  flutter_html: ^1.2.0
  sms_autofill: ^1.2.6
  permission: ^0.1.7
  flutter_inner_drawer: "^0.5.4"
  flutter_google_maps: ^4.0.0
  location_permissions: '^2.0.3'
  search_map_place:
  http: ^0.12.1
  geolocator: ^6.1.14
  weather: ^1.2.4
  image_cropper: ^1.3.1
  move_to_background: ^1.0.0
  image_picker: ^0.6.7+22
  qr_code_scanner: ^0.0.13
  flutter_webview_plugin: ^0.3.11
  flutter_inappwebview:
  fluttertoast: ^7.1.6
  flutter_countdown_timer:
  keyboard_visibility: any
  firebase_crashlytics: ^0.2.4
  image_picker_gallery_camera: ^0.1.6
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - lib/lang/en.json
    - lib/lang/fa.json
    - lib/lang/ar.json
    - lib/lang/hi.json
  # To add assets to your application, add an assets section, like this:
#   assets:
#     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.otf
        - asset: fonts/Montserrat-Bold.otf
        - asset: fonts/Montserrat-Medium.otf
        - asset: fonts/Montserrat-Regular.otf
    - family: Jeko
      fonts:
        - asset: fonts/Jeko/Jeko-ExtraBoldItalic.otf
        - asset: fonts/Jeko/Jeko-ExtraLightItalic.otf
        - asset: fonts/Jeko/Jeko-MediumItalic.otf
        - asset: fonts/Jeko/JekoSans-ExtraBold.otf
        - asset: fonts/Jeko/JekoSans-ExtraLight.otf
        - asset: fonts/Jeko/JekoSans-Medium.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
